version: '3'
services:
  jaeger:
    image: jaegertracing/all-in-one:1.6
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
      - "4317:4317"
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: doutorequemtemdoutorado  #
      MYSQL_DATABASE: books
      MYSQL_USER: books
      MYSQL_PASSWORD: doutorequemtemdoutorado
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  mysql-reviews:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: doutorequemtemdoutorado  #
      MYSQL_DATABASE: reviews
      MYSQL_USER: reviews
      MYSQL_PASSWORD: doutorequemtemdoutorado
    ports:
      - "3308:3306"
    volumes:
      - mysql_review_data:/var/lib/mysql

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  books-api:
    build: ./books
    environment: 
      OTEL_SERVICE_NAME: books-api
      OTEL_TRACES_EXPORTER: zipkin
      OTEL_EXPORTER_ZIPKIN_ENDPOINT: http://jaeger:9411/api/v2/spans
      OTEL_METRICS_EXPORTER: none
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: "com.mysql.cj.jdbc.Driver"
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/books"
      SPRING_DATASOURCE_USERNAME: "books"
      SPRING_DATASOURCE_PASSWORD: "doutorequemtemdoutorado"
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: false
      SPRING_JPA_SHOW_SQL: true
    ports:
      - "8090:8080"


# JAVA_TOOL_OPTIONS="-javaagent:pkg/opentelemetry-javaagent.jar";OTEL_TRACES_EXPORTER=zipkin;OTEL_METRICS_EXPORTER=none;OTEL_EXPORTER_ZIPKIN_ENDPOINT=http://localhost:9411/api/v2/spans;OTEL_SERVICE_NAME=bosta

volumes:
  mysql_data:
  mysql_review_data: